## Gradient Descent - Boston Dataset

generic GD +preprocessing features

In [26]:
import numpy as np

test_data=np.loadtxt("boston_test_data.csv",delimiter=",")
train_data= np.loadtxt("boston_train_data.csv",delimiter=",")





In [27]:
train_x=train_data[:,0:13]
train_y=train_data[:,13]

In [28]:
dummy_merge=np.append(train_x,test_data,axis=0)
dummy_merge

array([[-0.40784991, -0.48772236, -1.2660231 , ..., -0.30309415,
         0.41057102, -1.09799011],
       [-0.40737368, -0.48772236,  0.24705682, ...,  0.1130321 ,
         0.29116915, -0.52047412],
       [ 0.1251786 , -0.48772236,  1.01599907, ...,  0.80657583,
        -3.79579542,  0.89107588],
       ..., 
       [-0.41001449,  2.08745172, -1.37837329, ..., -0.0719129 ,
         0.39094481, -0.68167397],
       [-0.40317611, -0.48772236, -0.37597609, ...,  1.13022958,
         0.34007019,  0.20142086],
       [-0.13356344, -0.48772236,  1.2319449 , ..., -1.73641788,
        -2.93893082,  0.48877712]])

In [29]:
dummy_merge.shape

(506, 13)

In [30]:
from sklearn import preprocessing
poly = preprocessing.PolynomialFeatures(2)
# poly = preprocessing.PolynomialFeatures(interaction_only=True)
dummy_merge=poly.fit_transform(dummy_merge)

In [31]:
dummy_merge.shape

(506, 105)

In [32]:
dummy_merge

array([[  1.        ,  -0.40784991,  -0.48772236, ...,   0.16856856,
         -0.45080292,   1.20558228],
       [  1.        ,  -0.40737368,  -0.48772236, ...,   0.08477947,
         -0.15154601,   0.27089331],
       [  1.        ,   0.1251786 ,  -0.48772236, ...,  14.40806287,
         -3.38234174,   0.79401622],
       ..., 
       [  1.        ,  -0.41001449,   2.08745172, ...,   0.15283784,
         -0.2664969 ,   0.4646794 ],
       [  1.        ,  -0.40317611,  -0.48772236, ...,   0.11564773,
          0.06849723,   0.04057036],
       [  1.        ,  -0.13356344,  -0.48772236, ...,   8.63731436,
         -1.43648214,   0.23890307]])

In [33]:
from sklearn import preprocessing
dummy_merge=preprocessing.scale(dummy_merge)  #this converges very fast in GD
dummy_merge

# min_max_scaler_object = preprocessing.MinMaxScaler()
# dummy_merge= min_max_scaler_object.fit_transform(dummy_merge)

array([[ 0.        , -0.40784991, -0.48772236, ..., -0.27495639,
        -0.06574531,  0.13063592],
       [ 0.        , -0.40737368, -0.48772236, ..., -0.30266564,
         0.16649811, -0.46330607],
       [ 0.        ,  0.1251786 , -0.48772236, ...,  4.43407881,
        -2.34081592, -0.13089104],
       ..., 
       [ 0.        , -0.41001449,  2.08745172, ..., -0.28015857,
         0.07728852, -0.34016597],
       [ 0.        , -0.40317611, -0.48772236, ..., -0.29245743,
         0.33726641, -0.60966328],
       [ 0.        , -0.13356344, -0.48772236, ...,  2.52567833,
        -0.83069845, -0.48363406]])

In [34]:
dummy_merge=dummy_merge[:,1:105]
dummy_merge.shape

(506, 104)

In [35]:
dummy_merge=np.column_stack((dummy_merge,np.ones((506,), dtype=int)))

In [36]:
dummy_merge.shape

(506, 105)

In [37]:
  train_x=dummy_merge[0:379,:]

In [38]:
  test_data=dummy_merge[379:506,:]

In [39]:
def step_gd(train_x, train_y, learning_rate, slope):
    new_slope=np.zeros(train_x.shape[1])
    
    M=train_x.shape[0]
   
    for i in range(M):
        for j in range(train_x.shape[1]):
            x=train_x[i][j]
            y=train_y[i]
            new_slope[j] = -(2/M) * (y - (slope * train_x[i]).sum()) * x
        slope = slope - (learning_rate * new_slope)
    return slope

In [40]:
def cost(train_x,train_y,slope ):
    total_cost=0
     
    for i in range(train_x.shape[0]):
        Y=train_y[i]
        X=train_x[i]
        total_cost += (1/train_x.shape[0])*((Y-(slope*X).sum())**2)
                                            
    return total_cost

In [41]:
def gradient_descent(train_x,train_y, learning_rate, num_itr):
    slope=np.zeros(train_x.shape[1])
  
    for i in range(num_itr):
        slope=step_gd(train_x,train_y, learning_rate,slope)
        print(i, " Cost: ", cost(train_x,train_y, slope))
    return slope

In [42]:
learning_rate=0.25

num_itr=100
slope =gradient_descent(train_x,train_y,learning_rate, num_itr)
print("slope is ",slope)

0  Cost:  211.848530614
1  Cost:  82.7512041001
2  Cost:  37.9102140796
3  Cost:  21.3321603398
4  Cost:  14.8658118889
5  Cost:  12.145766673
6  Cost:  10.8692715
7  Cost:  10.1813221098
8  Cost:  9.75342022708
9  Cost:  9.45309431537
10  Cost:  9.22318607082
11  Cost:  9.03677100863
12  Cost:  8.87981753041
13  Cost:  8.74423797211
14  Cost:  8.62494488289
15  Cost:  8.5185118165
16  Cost:  8.42251119103
17  Cost:  8.33515745026
18  Cost:  8.25509899106
19  Cost:  8.18128870265
20  Cost:  8.11289929765
21  Cost:  8.04926583044
22  Cost:  7.98984555197
23  Cost:  7.93418923993
24  Cost:  7.88192034219
25  Cost:  7.83271955975
26  Cost:  7.78631328579
27  Cost:  7.74246482141
28  Cost:  7.70096761871
29  Cost:  7.66164002317
30  Cost:  7.62432113763
31  Cost:  7.58886753519
32  Cost:  7.55515062077
33  Cost:  7.52305449385
34  Cost:  7.49247420155
35  Cost:  7.46331429883
36  Cost:  7.43548765227
37  Cost:  7.40891443845
38  Cost:  7.38352129932
39  Cost:  7.35924062493
40  Cost:  7.33

In [523]:
# test_data=np.column_stack((test_data,np.ones((127,), dtype=int)))

In [43]:
y_test=np.matmul(test_data,slope)

In [44]:
Boston_sol = open('file'+'_2', 'w')
np.savetxt('Boston_sol.csv',y_test,delimiter=',')

In [526]:
# 499  Cost:  12.4916836271 11.5 //6.32
# slope is  [ -0.67753909   2.17814114  -1.22757613   2.0875015   -3.46169661
#   16.22446432  -0.16112207  -3.25878835   2.65439915  -4.19320857
#   -3.35839431   2.64436698 -15.94497764   0.04666306   2.28280696
#    0.04996824   4.46327185  -0.86051305   0.59659524  -0.29613791
#    3.01204094  -0.80079769  -0.18495637  -0.02573943   1.26426964
#   -0.22053119   1.77162982   0.27176731   1.19621928   1.7703928
#    1.82250976  -0.56260472   1.54726817   0.7823978    0.73944968
#    2.22592316   1.61913735   2.56560961   2.13390926   0.89337613
#    1.73610485  -3.78244643   3.6784105    0.87329514   1.80539581
#    0.77736679  -1.50831108   0.91563734  -2.50761137   2.0875015
#   -3.13590274  -0.1260848    1.66896489   0.56859556   2.18711758
#    2.32479489   2.84555204   2.92010603  -1.80924123  -2.61515006
#   -3.42500529  -0.95170335   3.08235325  -3.08470653  -1.76007763
#   -0.19712412   0.56417362   0.51161972   8.37815442  -0.87919122
#    2.34333038  -3.84771609  -4.05405765  -4.64018401   2.46777492
#   -4.19698366   2.00398413  -0.59706134   2.40706242   1.09970586
#   -0.6652558   -0.44036461  -3.63979076   2.70469544   0.20399942
#    1.36229882   2.63734289   0.17963605   5.72450684  -2.01955339
#    3.04515657   3.17161545   0.18158978  -3.44038285   0.26835018
#    3.39149506   0.03474212  -3.69693683   0.66036779   0.09554752
#    1.03468838  -0.65484388  -1.88670304   4.86569743   2.36214245]