In [14]:
import numpy as np

In [15]:
x = np.array([[0, 0], [1,0], [0,1], [1,1]])
y = np.array([[0,0,0,1]]).T
lr = 0.01

In [16]:
def sigmoid(z):
    return 1/(1 + np.exp(-z))

In [17]:
def derivativeSig(z):
    return sigmoid(z)*(1 - sigmoid(z))

In [18]:
# Weights, bias for hidden layer
weights_hid = 2 * np.random.random((2,2)) - 1
bias_hid = 2 * np.random.random((1, 2)) - 1
weights_hid, bias_hid

(array([[ 0.38788347,  0.31623846],
        [ 0.58660747, -0.835854  ]]), array([[-0.12433648,  0.71458722]]))

In [19]:
# Weights, bias for output layer
weights_output = 2 * np.random.random((2, 1)) - 1
bias_output    = 2 * np.random.random((1,1)) - 1
weights_output, bias_output

(array([[0.04784759],
        [0.06614023]]), array([[-0.49030298]]))

In [36]:
for i in range(10000):
    output0 = x
    input_hid = np.dot(output0, weights_hid) + bias_hid
    output_hid = sigmoid(input_hid)
    input_output_layer = np.dot(output_hid, weights_output) + bias_output 
    output = sigmoid(input_output_layer)

    first_term_output = output - y
    second_term_output = derivativeSig(input_output_layer)
    first_two_output = first_term_output * second_term_output

    first_term_hidden = np.dot(first_two_output, weights_output.T)
    second_term_hidden = derivativeSig(input_hid)
    first_two_hidden = first_term_hidden * second_term_hidden

    changes_output = np.dot(output_hid.T, first_two_output)
    changes_output_bias = np.sum(first_two_output, axis=1, keepdims=True)

    changes_hidden = np.dot(output0.T, first_two_hidden)
    changes_hidden_bias = np.sum(first_two_hidden, axis = 1, keepdims=True)

    weights_output = weights_output - lr*changes_output
    bias_output = bias_output - lr*changes_output_bias

    weights_hid = weights_hid - lr*changes_hidden
    bias_hid = bias_hid - lr*changes_hidden_bias

output0 = x
input_hid = np.dot(output0, weights_hid) + bias_hid
output_hid = sigmoid(input_hid)
input_output_layer = np.dot(output_hid, weights_output) + bias_output 
output = sigmoid(input_output_layer)
output

array([[0.01070447],
       [0.01110938],
       [0.01182594],
       [0.98150262]])