In [1]:
import numpy as np

In [2]:
x = np.array([[0, 0], [1,0], [0,1], [1,1]])
y = np.array([[0,0,0,1]]).T

In [3]:
def sigmoid(z):
    return 1/(1 + np.exp(-z))

In [7]:
# Weights, bias for hidden layer
weights_hid = 2 * np.random.random((2,2)) - 1
bias_hid = 2 * np.random.random((1, 2)) - 1
weights_hid, bias_hid

(array([[-0.88418222,  0.23681554],
        [-0.06299186, -0.10064925]]), array([[-0.49267009, -0.25831494]]))

In [10]:
# Weights, bias for output layer
weights_output = 2 * np.random.random((2, 1)) - 1
bias_output = 2 * np.random.random((1,1)) - 1
weights_output, bias_output

(array([[-0.5713814 ],
        [-0.31650241]]), array([[0.50659375]]))

In [11]:
output_hid = sigmoid(np.dot(x, weights_hid) + bias_hid)
output = sigmoid(np.dot(output_hid, weights_output) + bias_output)
output

array([[0.53791809],
       [0.55845687],
       [0.54193788],
       [0.56181622]])