In [18]:
import numpy as np

In [19]:
x = np.array([[0, 0], [1,0], [0,1], [1,1]])
y = np.array([[0,0,0,1]]).T

In [20]:
def sigmoid(z):
    return 1/(1 + np.exp(-z))

In [21]:
def derivativeSig(z):
    return sigmoid(z)*(1 - sigmoid(z))

In [22]:
weights = 2 * np.random.random((2,1)) - 1
bias = 2 * np.random.random(1) - 1
weights, bias

(array([[-0.54433725],
        [ 0.95714998]]), array([0.42977974]))

In [23]:
output = sigmoid(np.dot(x, weights) + bias)
output

array([[0.60582107],
       [0.4713919 ],
       [0.80010164],
       [0.69901094]])

In [24]:
lr = 0.01

In [25]:
for i in range(1000000):
    output = sigmoid(np.dot(x, weights) + bias)

    first_term = output - y
    input_second_term = np.dot(x, weights) + bias
    second_term = derivativeSig(input_second_term)
    first_two_term = second_term * first_term

    changes = np.dot(x.T, first_two_term)
    weights = weights - lr*changes

    change_bias = np.sum(first_two_term)
    bias = bias - lr*change_bias
final_output = sigmoid(np.dot(x, weights) + bias)
weights, bias , final_output

(array([[8.01853572],
        [8.01853572]]), array([-12.11426993]), array([[5.48071273e-06],
        [1.63710500e-02],
        [1.63710500e-02],
        [9.80598287e-01]]))