In [66]:
import numpy as np
data = np.loadtxt("train.csv",delimiter =",")

In [67]:
x=data[:,0:9]
y=data[:,10]
x


array([[-0.04910502, -0.04464164,  0.16085492, ..., -0.04708248,
         0.03430886,  0.02801651],
       [-0.07090025,  0.05068012, -0.08919748, ..., -0.03235593,
        -0.00259226, -0.01290794],
       [ 0.00175052, -0.04464164, -0.07087468, ...,  0.02655027,
        -0.03949338, -0.02251217],
       ..., 
       [ 0.02354575, -0.04464164,  0.0703187 , ..., -0.03235593,
        -0.00259226, -0.01919705],
       [ 0.01628068,  0.05068012,  0.07247433, ..., -0.00658447,
        -0.00259226, -0.02364456],
       [-0.00914709,  0.05068012, -0.03099563, ..., -0.02131102,
        -0.00259226,  0.00620932]])

In [73]:
x=data[:,0:9]


In [71]:
from sklearn.linear_model import LinearRegression
alg1 = LinearRegression()


In [74]:
alg1.fit(x,y)


LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [45]:
m = alg1.coef_[0]
c = alg1.intercept_

In [76]:
data2 = np.loadtxt("test.csv",delimiter=",")
x_test = data2[:,0:9]

In [78]:
y_pred = alg1.predict(x_test)
y_pred

array([ 104.93961977,  107.86922942,  180.08364153,   82.75039371,
         52.91162344,  101.07109954,  153.95734749,   32.74164014,
        112.28452824,  161.35070824,  135.28804079,   90.31800962,
        139.47084586,  140.37312699,  158.6293397 ,  172.15700004,
        109.41264986,  109.11137939,   96.66350249,  167.06527844,
        168.73346718,  100.6425075 ,  254.51629196,  146.49550095,
        214.54098847,  165.43543975,  212.40185948,   69.0042563 ,
        187.1483223 ,  201.11544672,  219.58065285,  169.58219647,
        115.52979923,  178.92653231,   74.87047266,   63.9979301 ,
        110.40156292,  156.36269043,  149.54250248,  203.10169058,
        113.23314961,  152.46169054,   84.48633763,  112.02771132,
        141.73253021,  148.41946629,   82.8785808 ,   72.35293885,
        127.58302305,  262.18260717,  212.55086052,  242.89542671,
        169.77201207,  185.99517001,  170.60000439,  203.03122121,
        215.40688385,  176.48613586,  175.84287433,  112.52581

In [49]:
def predict(x,m,c):
    return m*x + c

In [50]:
y_pred_2 = predict(x_test,m,c)
y_pred_2

array([[ 0.00501327],
       [-0.0177    ],
       [-0.00715456],
       [-0.00147624],
       [-0.00472099],
       [-0.00796574],
       [-0.00228743],
       [-0.01202168],
       [ 0.00176851],
       [-0.02013356],
       [ 0.00176851],
       [-0.00958812],
       [-0.01039931],
       [ 0.01555871],
       [ 0.00582445],
       [-0.00147624],
       [-0.02094475],
       [-0.00634337],
       [ 0.00176851],
       [ 0.00582445],
       [-0.01445525],
       [ 0.00176851],
       [ 0.00501327],
       [ 0.00582445],
       [ 0.0025797 ],
       [ 0.01799227],
       [-0.00066505],
       [-0.02256713],
       [-0.00796574],
       [ 0.00176851],
       [ 0.01312515],
       [ 0.00420208],
       [ 0.00014614],
       [-0.01039931],
       [-0.00634337],
       [ 0.00014614],
       [ 0.00420208],
       [ 0.00176851],
       [ 0.00014614],
       [-0.01364406],
       [-0.00796574],
       [ 0.0025797 ],
       [-0.0039098 ],
       [ 0.00501327],
       [-0.01364406],
       [ 0